etcd_min_cluster_size: 3
etcd_max_cluster_size: 3
etcd_launch:
  instance_type: t3.small
  key_name: "{{ ssh_key.aws_label }}"
  user_data: "{{ lookup('template', 'ec2_user_data.yml') }}"
  instance_profile_name: kube_master
  volumes:
    - device_name: /dev/xvdb
      ebs:
        delete_on_termination: yes
        volume_size: 20
        volume_type: gp2
  version: "{{ universal_image_version }}"
ssh_key:
  aws_label: aws_id_rsa
  local_path: ~/.ssh/aws_id_rsa
