apiVersion: v1
kind: Namespace
metadata:
  name: autoscaler
spec:
  finalizers:
  - kubernetes
---
apiVersion: v1
kind: Service
metadata:
  name: autoscaler
  namespace: autoscaler
  labels:
    app: autoscaler
  annotations:
spec:
  selector:
    app: autoscaler
  ports: 
    - protocol: TCP
      port: 8080
      containerPort: 8080
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: selfsigned-issuer
  name: autoscaler
  namespace: autoscaler
spec:
  tls:
    - hosts:
      - autoscaler.randomuser.org
      secretName: autoscaler-tls
  rules: 
    - host: autoscaler.randomuser.org
      http:
        paths:
          - backend:
              serviceName: autoscaler
              servicePort: 8080
