---
- include: os_tune.yml
- include: repo_setup.yml
- set_fact:
    install_set: "{{ install_set | default([]) + ['%s%s' % (item, '-%s' % kube_release if 'kube' in item else '')] }}"
  with_items: "{{ role_packages }}"
- debug: var=install_set
- name: install packages
  become: true
  dnf:
    name: "{{ install_set }}"
    state: present
    allow_downgrade: yes
- name: make life easy for the service user
  become: true
  user:
    name: fedora
    groups: docker
    append: yes
- name: install python modules for which there are not RPMs
  pip:
    name: "{{ pip_extra_modules }}"
    state: present
    extra_args: "--user"
  when: ( pip_extra_modules is defined )
- name: install etcd3 python module
  become: true
  pip:
    name: etcd3
    state: present
    extra_args: "--user"
 
- name: create docker service dropin dir
  become: true
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
- name: override docker service exec
  become: true
  copy:
    dest: /etc/systemd/system/docker.service.d/10_EnvironmentFile.conf
    content: |
        [Service]
        EnvironmentFile=/etc/sysconfig/docker
        ExecStart=
        ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock $DOCKERD_OPTS
  register: docker_systemd
- name: set docker options
  become: true
  copy:
    dest: /etc/sysconfig/docker
    content: 'DOCKERD_OPTS="{% for option in docker_daemon_options %} {{ option }} {% endfor %}"'
  register: docker_opts
- name: reload systemd
  become: true
  systemd:
    daemon-reload: yes
  when: ( docker_systemd.changed )

- name: turn up services
  become: true
  service:
    name: "{{ item }}"
    state: "{{ 're' if ( docker_opts.changed and item == 'docker' ) else '' }}started"
    enabled: yes
  with_items: 
    - kubelet
    - docker
# this is just a sanity check, not changeful
- name: prep image pull
  become: true
  shell: kubeadm config images pull
  register: config_images_pull
  changed_when: false
# https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/
- name: copy cluster resource template
  template: 
    src: kubeadm-config.yaml.j2
    dest: "/home/{{ ansible_user }}/kubeadm-config.yaml.j2"
- include: kube_ca.yml
- name: copy helper script
  become: true
  copy:
    src: cluster_bootstrap.py
    dest: /usr/local/bin/
    mode: 0755


