- include_tasks: boot_args.yml
- name: selinux in permissive, for now
  become: true
  selinux:
    policy: targeted
    state: permissive
  register: selinux_state
- name: set hostname
  become: true
  hostname:
    name: "{{ inventory_hostname }}"
  register: host_name
- reboot:
  become: true
  when: ( selinux_state.changed or grub_args.changed or host_name.changed )
- name: load the bridge and overlay  modules
  become: true
  modprobe:
    name: "{{ item }}"
    state: present
  with_items:
    - br_netfilter
    - overlay
- name: on boot too
  become: true
  lineinfile:
    line: "{{ item }}"
    path: /etc/modules-load.d/container_host.conf
    create: yes
  with_items:
    - br_netfilter
    - overlay
- name: adjust sysctl parameters 
  become: true
  sysctl:
    name: "{{ item.p }}"
    value: "{{ item.v }}"
    reload: yes
    sysctl_file: /etc/sysctl.d/kube_recs.conf
  with_items: "{{ sysctl_parameters }}"
- name: configure hostfile
  become: true
  template:
    src: templates/hostfile.j2
    dest: /etc/hosts
