apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: selfsigned-issuer
  name: canary-ingress
  namespace: default
spec:
  tls:
    - hosts:
      - canary.randomuser.org
      secretName: canary-tls
  rules:
    - host: canary.randomuser.org
      http:
        paths:
          - backend:
              serviceName: canary
              servicePort: 9950
  
