---
apiVersion: v1
kind: Service
metadata:
  name: canary
  labels:
    app: canary
  annotations:
spec:
  selector:
    app: canary
  ports: 
    - protocol: TCP
      port: 9950
      targetPort: 80
      name: canary-http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: canary-deploy
  labels:
    app: canary
spec:
  replicas: 3
  selector: 
    matchLabels:
      app: canary
  template:
    metadata: 
      labels:
        app: canary
    spec:
      containers:
        - name: canary
          image: nginx
          ports:
            - protocol: TCP
              containerPort: 80
              name: canary
---


