- name: bootstrap etcd
  hosts: ec2-etcd
  gather_facts: false
  tasks:
    - include_role:
        name: ec2_bootstrap
      tags: ['always']
    - include_role:
        name: cluster_common
      tags: ['common']
    - include_role:
        name: etcd
      tags: ['etcd']
    - include_role:
        name: kube_init
- name: bootstrap kube
  hosts: ec2-k8s
  gather_facts: false
  tasks:
    - include_role:
        name: ec2_bootstrap
      tags: ['always']
    - include_role: 
        name: cluster_common
      tags: ['common']
    - include_role:
        name: elb_creator
      tags: ['elb']
      vars:
        listen_port: 6443
        instance_port: 6443
    - include_role:
        name: kube_builder
      tags: ['kube_builder']
