- name: enforce IAM
  hosts: localhost
  gather_facts: smart
  tasks:
    - include_role:
        name: cluster_iam
        apply: 
          tags: ['iam']
      tags: ['iam']
- name: set up container registry
  hosts: localhost
  gather_facts: smart
  tasks:
    - include_role:
        name: cluster_ecr
        apply: 
          tags: ['ecr']
      tags: ['ecr']

- name: purge nodes
  hosts: ec2-k8s:ec2-etcd:ec2-worker
  gather_facts: smart
  vars:
    state: absent
  tasks:
    - include_role:
        name: ec2_bootstrap
        apply:
          tags: 
            - purge
            - never
      tags: ['purge', 'never']
- name: bootstrap nodes
  hosts: ec2-k8s:ec2-etcd:ec2-worker
  gather_facts: smart
  vars:
    cluster_name: cluster0
  tasks:
    - include_role:
        name: ec2_bootstrap
        apply:
          tags: ['always']
      tags: ['always']
    - name: reboot
      become: true
      reboot:
      tags: ['never', 'reboot']
    - include_role:
        name: cluster_common
        apply:
          tags: ['common']
      tags: ['common']
- name: bring up etcd
  hosts: ec2-etcd
  gather_facts: smart
  tasks:
    - include_role:
        name: etcd
        apply:
          tags: ['etcd']
      tags: ['etcd']
- name: bring up the cluster
  hosts: ec2-k8s
  gather_facts: smart
  vars:
    cluster_name: cluster0
  tasks:
    - name: reset, maybe
      become: true
      shell: yes | kubeadm reset
      tags: ['never', 'reset']
    - include_role:
        name: elb_creator
        apply:
          tags: ['elb', 'always']
      tags: ['elb', 'always']
      vars:
        listen_port: 6443
        instance_port: 6443
    - include_role:
        name: kube_builder
        apply:
          tags: ['kube_builder']
      tags: ['kube_builder']
    - include_role:
        name: nginx_ingress
        apply:
          tags: ['ingress']
      tags: ['ingress']
- name: join the workers
  hosts: ec2-worker
  gather_facts: smart
  tasks:
    - name: reset, maybe
      become: true
      shell: yes | kubeadm reset
      tags: ['never', 'reset']
    - include_role:
        name: kube_worker
        apply:
          tags: ['worker']
      tags: ['worker']
    - include_role:
        name: cert-manager
        apply:
          tags: ['cert-manager']
      tags: ['cert-manager']
      run_once: true
    - include_role:
        name: canary
        apply:
          tags: ['canary']
      tags: ['canary']
      run_once: true

- name: whatever
  hosts: ec2-k8s:ec2-worker
  gather_facts: smart
  tasks:
    - shell: "{{ whatever }}"
      become: true
      register: thatswhat
      when: ( whatever is defined )
      tags: ['whatever', 'never']
    - debug: var=thatswhat.stdout_lines
      when: ( whatever is defined )
      tags: ['whatever', 'never']
  
