---
- name: bring up node and image it
  hosts: ec2-baseimage
  gather_facts: false
  vars_files:
    - vars/main.yml
  tasks:
    - include_role: 
        name: ec2_bootstrap
    - include_role: 
        name: cluster_common
        apply:
          tags: ['common']
      tags: ['common']
    - include_role:
        name: etcd_autoscale/image_prep
        apply:
          tags: ['etcd']
      tags: ['etcd']
    - include_role:
        name: kube_builder/image_prep
        apply:
          tags: ['kube_prep']
      tags: ['kube_prep']
    - include_role:
        name: create_image
        apply:
          tags: ['image']
      tags: ['image']
    - name: destroy the instance
      delegate_to: localhost
      ec2_instance: 
        instance_role: kube_master
        state: absent
        profile: "{{ aws_profile }}"
        image_id: "{{ image_id }}"
        instance_type: "{{ instance_type }}"
        key_name: "{{ ssh_key.aws_label }}"
        name: "{{ inventory_hostname }}"
        region: "{{ region }}"
        tags: "{{ { 'kubernetes.io/cluster/%s' % cluster_name: 'fancy', 'KubernetesCluster': cluster_name } }}"
        user_data: "{{ user_data | default(omit) }}"
        vpc_subnet_id: "{{ subnet_id }}"
      register: instances

