---
- name: bring up node and image it
  hosts: ec2-baseimage
  gather_facts: false
  vars_files:
    - vars/main.yml
  tasks:
    - include_role: 
        name: ec2_bootstrap
    - include_role: 
        name: cluster_common
        apply:
          tags: ['common']
      tags: ['common']
    - include_role:
        name: etcd_autoscale/image_prep
        apply:
          tags: ['etcd']
      tags: ['etcd']
    - include_role:
        name: kube_builder/image_prep
        apply:
          tags: ['kube_prep']
      tags: ['kube_prep']
    - include_role:
        name: create_image
        apply:
          tags: ['image']
      tags: ['image']
