---
role_packages:
  - kubelet
  - kubeadm
  - kubectl
  - containerd.io
  - device-mapper-persistent-data
  - lvm2
  - docker-ce
  - docker-ce-cli
docker_daemon_options:
  - "--exec-opt native.cgroupdriver=systemd"
  - "--dns-search randomuser.org"
