- name: generate ca certs
  become: true
  shell:  >
    kubeadm init --config /home/{{ ansible_user }}/kubeadm-config.yaml phase certs ca
    creates=/etc/kubernetes/pki/ca.key
  register: phase_certs_ca
- name: generate front proxy cacert
  become: true
  shell:  >
    kubeadm init --config /home/{{ ansible_user }}/kubeadm-config.yaml phase certs front-proxy-ca
    creates=/etc/kubernetes/pki/front-proxy-ca.key
  register: phase_frontproxy_ca
- name: generate apiserver certs
  become: true
  shell:  >
    kubeadm init --config /home/{{ ansible_user }}/kubeadm-config.yaml phase certs apiserver
    creates=/etc/kubernetes/pki/apiserver.key
  register: phase_certs_apiserver
- name: generate apiserver client certs for kubelet
  become: true
  shell:  >
    kubeadm init --config /home/{{ ansible_user }}/kubeadm-config.yaml phase certs apiserver-kubelet-client
    creates=/etc/kubernetes/pki/apiserver-kubelet-client.key
  register: phase_certs_apiserver_kubelet_client
- name: generate front-proxy client certs
  become: true
  shell:  >
    kubeadm init --config /home/{{ ansible_user }}/kubeadm-config.yaml phase certs front-proxy-client
    creates=/etc/kubernetes/pki/front-proxy-client.key
  register: phase_certs_frontproxy_client
- name: kubeadm init phase certs sa
  become: true
  shell:  >
    kubeadm init phase certs sa
    creates=/etc/kubernetes/pki/sa.key
  register: kube_init
- debug:
    msg: |
      {{ phase_preflight.stdout | default('') }}
      {{ phase_kubelet.stdout | default('') }}
      {{ phase_certs_ca.stdout | default('') }}
      {{ phase_frontproxy_ca.stdout | default('') }}
      {{ phase_certs_apiserver.stdout | default('') }}
      {{ phase_certs_apiserver_kubelet_client.stdout | default('') }}
      {{ phase_certs_frontproxy_client.stdout | default('') }}
      {{ kube_init.stdout | default('') }}
- fail:
  when: certs_only is defined
