- name: kubeadm kubeconfig admin
  become: true
  shell: >
    kubeadm init --config /home/{{ ansible_user }}/kubeadm-config.yaml phase kubeconfig admin
    creates=/etc/kubernetes/admin.conf
  register: phase_kubeconfig_admin
- name: kubeadm kubeconfig kubelet
  become: true
  shell: >
    kubeadm init --config /home/{{ ansible_user }}/kubeadm-config.yaml phase kubeconfig kubelet --node-name {{ inventory_hostname }}
    creates=/etc/kubernetes/kubelet.conf
  register: phase_kubeconfig_kubelet
- name: kubeadm kubeconfig controller-manager
  become: true
  shell: >
    kubeadm init --config /home/{{ ansible_user }}/kubeadm-config.yaml phase kubeconfig controller-manager
    creates=/etc/kubernetes/controller-manager.conf
  register: phase_kubeconfig_controller_manager
- name: kubeadm kubeconfig scheduler
  become: true
  shell: >
    kubeadm init --config /home/{{ ansible_user }}/kubeadm-config.yaml phase kubeconfig scheduler
    creates=/etc/kubernetes/scheduler.conf
  register: phase_kubeconfig_scheduler
- name: dump info
  debug:
    msg: |

