# kubeadm init phase control-plane
- name: kubeadm init phase control-plane apiserver
  become: true
  shell: >
    kubeadm init --config /home/{{ ansible_user }}/kubeadm-config.yaml phase control-plane apiserver
    creates=/etc/kubernetes/manifests/kube-apiserver.yaml
  register: phase_controlplane_apiserver
- name: kubeadm init phase control-plane controller-manager
  become: true
  shell: >
    kubeadm init --config /home/{{ ansible_user }}/kubeadm-config.yaml phase control-plane controller-manager
    creates=/etc/kubernetes/manifests/kube-controller-manager.yaml
  register: phase_controlplane_controllermanager
- name: kubeadm init phase control-plane scheduler
  become: true
  shell: >
    kubeadm init --config /home/{{ ansible_user }}/kubeadm-config.yaml phase control-plane scheduler
    creates=/etc/kubernetes/manifests/kube-scheduler.yaml
  register: phase_controlplane_scheduler
