- name: create template directory
  become: true
  file:
    path: /usr/local/share/k8s_autoscale/
    state: directory
- name: copy cluster configuration template
  become: true
  copy:
    src: kubeadm-config.yaml.j2
    dest: /usr/local/share/k8s_autoscale/kubeadm-config.yaml.j2
