- name: allow instances to assume roles
  iam_role:
    assume_role_policy_document: >
      {   
         "Version": "2012-10-17",
         "Statement": [
           {
             "Effect": "Allow",
             "Principal": {
               "Service": "ec2.amazonaws.com"
             },
             "Action": "sts:AssumeRole"
           }
         ]
      }   
    profile: "{{ aws_profile }}"
    name: k8s_master_node
    state: present
    region: "{{ region }}"
    purge_policies: yes 
    create_instance_profile: yes 
  register: kube_master_role
- name: create iam policy for masters
  run_once: true
  delegate_to: localhost
  iam_policy:
    profile: "{{ aws_profile }}"
    region: "{{ region }}"
    iam_name: k8s_master_node
    iam_type: role
    policy_name: 
    policy_json: "{{ lookup('template', 'kube_master_iam_policy.json') }}"
    state: present

      
