- name: apply manditory resource definitions
  k8s:
    apply: yes
    resource_definition: "{{ lookup('template', 'mandatory.yaml') }}"
- name: create layer 4 ingress service
  k8s:
    apply: yes
    resource_definition: "{{ lookup('template', 'service-l4.yaml') }}"
- name: patch nginx configmap
  k8s:
    apply: yes
    resource_definition: "{{ lookup('template', 'patch-configmap-l4.yaml') }}"
