- name: pull etc podman image
  become: true
  podman_image: 
    name: quay.io/coreos/etcd
    pull: yes
    state: present
    tag: "{{ etcd_tag | default('latest') }}"
- name: drop unit file
  become: true
  copy:
    content: "{{ lookup('template', 'templates/etcd.service.j2') }}"
    dest: /etc/systemd/system/etcd.service
  register: unit_file
- name: reload systemd
  become: true
  systemd:
    daemon-reload: yes
  when: ( unit_file.changed )
- name: enable service
  become: true
  systemd:
    name: etcd
    state: "{{ 're' if unit_file.changed else ''}}started"
    enabled: yes

