---
- name: define launch config
  run_once: true
  delegate_to: localhost
  ec2_lc:
    name: "{{ item }}"
    profile: "{{ aws_profile }}"
    image_id: "{{ launch_configs[item].get('image_id') }}"
    instance_type: "{{ launch_configs[item].get('instance_type') }}"
    key_name: "{{ ssh_key.aws_label }}"
    volumes: "{{ launch_configs[item]['volumes'] |default(omit) }}"
  with_items: "{{ launch_configs.keys()|list }}"

- name: define autoscaling group
  run_once: true
  delegate_to: localhost
  ec2_asg:
    profile: "{{ aws_profile }}"
    name: "asg_worker_{{ item }}"
    default_cooldown: 300
    health_check_period: 120
    health_check_type: EC2
    launch_config_name: "{{ item }}"
    metrics_collection: no
    min_size: 0
    max_size: 9
    region: "{{ region }}"
    replace_all_instances: yes
    vpc_zone_identifier: 
      - "{{ subnet_id }}"
  with_items: "{{ launch_configs.keys()|list }}"


    





