- include_tasks: create_asg.yml
- name: set up namespace and service
  delegate_to: localhost
  k8s:
    apply: yes
    resource_definition: "{{ lookup('template', 'autoscaler-namespace-service.yaml' ) }}"
    kubeconfig: "{{ playbook_dir }}/local_cache/kubectl.conf"
- name: set up deployment
  delegate_to: localhost
  k8s:
    apply: yes
    resource_definition: "{{ lookup('template', 'deployment.yaml' ) }}"
    kubeconfig: "{{ playbook_dir }}/local_cache/kubectl.conf"
