- name: define launch config
  run_once: true
  delegate_to: localhost
  ec2_lc:
    name: ec2_launch
    profile: "{{ aws_profile }}"
    image_id: "{{ ec2_launch.image_id }}"
    instance_type: "{{ ec2_launch.instance_type }}"
    key_name: "{{ ssh_key.aws_label }}"
    volumes: "{{ ec2_launch.volumes | default(omit) }}"

- name: define autoscaling group
  run_once: true
  delegate_to: localhost
  ec2_asg:
    profile: "{{ aws_profile }}"
    name: "etcd_{{ cluster_name }}"
    default_cooldown: 300
    health_check_period: 120
    health_check_type: EC2
    launch_config_name: "{{ item }}"
    metrics_collection: no
    min_size: "{{ etcd_min_cluster_size }}"
    max_size:  "{{ etcd_max_cluster_size }}"
    region: "{{ region }}"
    replace_all_instances: yes
    vpc_zone_identifier: 
      - "{{ subnet_id }}"
  with_items: "{{ launch_configs.keys()|list }}"

