- name: ship cni config
  delegate_to: localhost
  run_once: true
  k8s:
    resource_definition: "{{ lookup('template', '%s.yml.j2' % cni_plugin )}}"
    apply: yes
    kubeconfig: "{{ playbook_dir }}/local_cache/kubectl.conf"
