---
kubelet_service_arguments:
  - "--node-ip {{ private_ip }}"
  #  - "--pod-manifest-path=/etc/kubernetes/manifests"
  - "--cgroup-driver=systemd"
  - "--provider-id=aws://us-west-2a/{{ instance_id }}"
kube_api_version: v1beta2
