- debug: var=ansible_user
- become: true
  debug: var=ansible_user
- name: create kube config dir
  become: true
  file: 
    path: "{{ '/home' if item != 'root' else '' }}/{{ item }}/.kube"
    state: directory
    owner: "{{ item }}"
    group: "{{ item }}"
  with_items: 
    - "{{ ansible_user }}"
    - root
- name: ship the kubeconfig
  become: true
  copy: 
    dest: "{{ '/home' if item != 'root' else '' }}/{{ item }}/.kube/config"
    src: "{{ playbook_dir }}/local_cache/kubectl.conf"
    owner: "{{ item }}"
    group: "{{ item }}"
  with_items: 
    - "{{ ansible_user }}"
    - 'root'
- name: get a join command
  become: true
  shell: >
    eval $( kubeadm token create --print-join-command )
    creates=/var/lib/kubelet/config.yaml
  register: cmd
- debug: var=cmd
