- name: create kube config dir
  file: 
    path: "/home/{{ ansible_user }}/.kube"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
- name: ship the kubeconfig
  copy: 
    src: "{{ playbook_dir }}/local_cache/kubectl.conf"
    dest: "/home/{{ ansible_user }}/.kube/config"
- name: get a join command
  become: true
  shell: >
    eval $(kubeadm --config /home/{{ ansible_user }}/.kube/config token create --print-join-command)
  register: cmd
- debug: var=cmd
