- name: create kube config dir
  file: 
    path: "/home/{{ ansible_user }}/.kube"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
- name: ship the kubeconfig
  copy: 
    src: kubectl.conf
    dest: "/home/{{ ansible_user }}/.kube/config"
