- name: create kube config dir
  become: true
  file: 
    path: "{{ '/home' if item != 'root' else '' }}/{{ item }}/.kube"
    state: directory
    owner: "{{ item }}"
    group: "{{ item }}"
  with_items: 
    - "{{ ansible_user }}"
    - root
- name: ship the kubeconfig
  become: true
  copy: 
    dest: "{{ '/home' if item != 'root' else '' }}/{{ item }}/.kube/config"
    src: "{{ playbook_dir }}/local_cache/kubectl.conf"
    owner: "{{ item }}"
    group: "{{ item }}"
  with_items: 
    - "{{ ansible_user }}"
    - 'root'
- name: get a join command
  shell: >
    kubeadm token create --print-join-command
  register: cmd
- set_fact:
    new_token: "{{ cmd.stdout.split()[4] }}"
    api_endpoint: "{{ cmd.stdout.split()[2] }}"
    token_hash: "{{ cmd.stdout.split()[6] }}"
- name: ship join config
  template:
    src: joinconfiguration.yaml.j2
    dest: "/home/{{ansible_user}}/bootstrap.conf"
- name: join the node
  become: true
  shell: >
    kubeadm join --config /home/{{ansible_user}}/bootstrap.conf --ignore-preflight-errors="FileAvailable--etc-kubernetes-kubelet.conf,FileAvailable--etc-kubernetes-pki-ca.crt"
  register: join_results
- debug: var=join_results
