- include_tasks: worker_iam.yml
- name: find image
  ec2_ami_info:
    profile: "{{ aws_profile }}"
    owner: "self"
    region: "{{ region }}"
    filters:
      name: "{{ cluster_name }}-universal"
      tag:randomuser.org/hamburger: "true"
      tag:randomuser.org/version: "{{ asg_image_version }}"
  register: latest_image
- debug:
    msg: "Fail here if no images match"
  when: ( latest_image.images | length < 1 )
- fail:
  failed_when: ( latest_image.images | length < 1 )
- debug: var=latest_image
- set_fact:
    use_ami: "{{ latest_image.images[0].image_id }}"
- name: purge old lc
  ec2_lc:
    profile: "{{ aws_profile }}"
    name: "{{ cluster_name }}-worker-launch"
    state: absent
- name: define worker launch config
  ec2_launch_template:
    template_name: "{{ cluster_name }}-worker-launch"
    region: "{{ region }}"
    profile: "{{ aws_profile }}"
    image_id: "{{ use_ami }}"
    instance_type: "{{ launch.instance_type }}"
    iam_instance_profile: "{{ launch.instance_profile }}"
    default_version: "latest"
    key_name: "{{ ssh_key.aws_label }}"
    user_data: "{{ lookup('template', 'kube_worker_user_data.yml') |b64encode }}"
    block_device_mappings: "{{ launch.volumes | default(omit) }}"
    tags:
      randomuser.org/usage: kube_worker
      randomuser.org/launch_version: "{{ launch.version| default('0.2') }}"
      KubernetesCluster: "{{ cluster_name }}"
  register: lt
- debug: var=lt

- name: instantiate k8s autoscaling group
  ec2_asg:
    profile: "{{ aws_profile }}"
    name: "{{ cluster_name }}-k8s-worker0"
    default_cooldown: 300
    health_check_period: 300
    health_check_type: EC2
    launch_template:
      launch_template_name: "{{ cluster_name }}-worker-launch"
      version: "$Latest"
    termination_policies: OldestLaunchConfiguration
    metrics_collection: no
    min_size: 0
    max_size: 5
    desired_capacity: 0
    region: "{{ region }}"
    replace_all_instances: no
    vpc_zone_identifier:
      - "{{ subnet_id }}"
    tags:
      - randomuser.org/usage: kube_worker
      - KubernetesCluster: "{{ cluster_name }}"
      - k8s.io/cluster-autoscaler/enabled: "True"
